version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./devops/docker/Dockerfile
        image: haynestec/jetstream.blog.server
        restart: always
        entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -wait-retry-interval 10s scripts/entrypoint.sh"
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www/html'
        networks:
            - server
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - server
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
        volumes:
            - "./scripts/mysql_testing.sql:/docker-entrypoint-initdb.d/mysql_testing.sql"

    redis:
        image: redis:latest
        restart: always
        command: "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - "6379:6379"
        networks:
            - server

networks:
    server:
        driver: bridge
